dist: bionic
language: node_js
node_js:
  - 12
addons:
  mariadb: '10.4'
env:
  - DB_HOST=localhost DB_PASS=testing DB_USER=testing DB_NAME=testing PAGE_URL=http://localhost:8080/ DEVS=1024
before_install:
  - sudo mysql -e 'create database testing  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
  - sudo mysql -e "CREATE USER testing IDENTIFIED BY 'testing'; GRANT ALL ON testing.* to testing;"
install:
  - npm install
before_script:
  - npm run migrate:test
script:
  - npm list discord.js
  - npm list discord-akairo
  - npm run lint
  - npm run coverage
after_success:
  - curl -s https://codecov.io/bash | bash
